version: '3.4'

services:
  server:
    image: server
    ports:
      - 3000:3000
    networks: 
      - api-hrm
    depends_on: 
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - 27017:27017
    networks: 
      - api-hrm
    volumes: 
      - mongo-data:/data/db
networks: 
  api-hrm:
    driver: bridge
volumes: 
  mongo-data:
    driver: local